include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    use_build_context_synchronously: warning
    prefer_final_fields: ignore
    curly_braces_in_flow_control_structures: ignore

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    curly_braces_in_flow_control_structures: false
