import React, { useEffect, useRef, useState } from 'react';
import { Smartphone, Monitor, CheckCircle2, AlertCircle, TrendingUp } from 'lucide-react';

const ProblemSolution: React.FC = () => {
  const [visible, setVisible] = useState(false);
  const sectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.15 }
    );
    if (sectionRef.current) observer.observe(sectionRef.current);
    return () => observer.disconnect();
  }, []);

  return (
    <section id="careers" ref={sectionRef} className="py-24 bg-white dark:bg-slate-950 relative overflow-hidden">
      {/* Subtle background accent */}
      <div className="absolute right-0 top-1/2 -translate-y-1/2 w-[400px] h-[400px] bg-teal-50/60 dark:bg-teal-900/10 rounded-full blur-[100px] pointer-events-none" />

      <div className="max-w-[1440px] mx-auto px-6 md:px-12">
        <div className="grid lg:grid-cols-2 gap-20 items-center">

          {/* ── LEFT: Slide in from left ── */}
          <div
            className={`space-y-10 transition-all duration-700 ${visible ? 'animate-slide-left' : 'opacity-0'}`}
          >
            <div>
              <div className="inline-flex items-center gap-2 text-teal-600 dark:text-teal-400 font-bold text-[11px] uppercase tracking-widest mb-5 px-4 py-2 rounded-full bg-teal-50 dark:bg-teal-900/30 border border-teal-100 dark:border-teal-800">
                <TrendingUp size={13} /> The Problem
              </div>
              <h2 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight leading-[1.1] mb-6">
                BiT students deserve<br />
                <span className="text-careermap-teal">structured guidance.</span>
              </h2>
              <p className="text-slate-500 dark:text-slate-400 font-medium text-lg leading-relaxed">
                Most BiT students graduate without a clear career path. CareerGuide fills that gap with AI-driven
                roadmaps, teacher-curated resources, and real-time progress monitoring — so no student is left behind.
              </p>
            </div>

            {/* Problem / Solution cards */}
            <div className="grid sm:grid-cols-2 gap-5">
              <div className="p-7 rounded-2xl border border-red-100 dark:border-red-900/40 bg-red-50/50 dark:bg-red-900/10 group hover:border-red-300 dark:hover:border-red-700 transition-all duration-300">
                <AlertCircle className="text-red-400 mb-4" size={24} />
                <h4 className="font-bold text-slate-900 dark:text-white mb-2">Without CareerGuide</h4>
                <p className="text-slate-500 dark:text-slate-400 text-sm font-medium leading-relaxed">
                  No clear direction, outdated resources, no teacher feedback, and no visibility into progress.
                </p>
              </div>
              <div className="p-7 rounded-2xl border border-teal-100 dark:border-teal-800/50 bg-teal-50/50 dark:bg-teal-900/10 group hover:border-teal-400 dark:hover:border-teal-600 transition-all duration-300">
                <CheckCircle2 className="text-teal-500 mb-4" size={24} />
                <h4 className="font-bold text-slate-900 dark:text-white mb-2">With CareerGuide</h4>
                <p className="text-slate-500 dark:text-slate-400 text-sm font-medium leading-relaxed">
                  AI roadmaps, teacher resources, live feedback, assessments, and progress dashboards in one place.
                </p>
              </div>
            </div>
          </div>

          {/* ── RIGHT: Slide in from right ── */}
          <div
            className={`grid grid-cols-2 gap-5 transition-all duration-700 ${visible ? 'animate-slide-right' : 'opacity-0'}`}
          >
            {/* Platform card */}
            <div className="bg-slate-900 dark:bg-slate-800 border border-slate-700 rounded-3xl p-10 text-white flex flex-col justify-between aspect-square hover:-translate-y-2 transition-transform duration-300">
              <Monitor className="text-teal-400" size={40} />
              <div>
                <h4 className="text-2xl font-bold mb-1">AI Roadmaps</h4>
                <p className="text-slate-400 text-base font-medium">Generated by Google Gemini for your career.</p>
              </div>
            </div>

            {/* Mobile card */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-3xl p-10 flex flex-col justify-between aspect-square shadow-sm hover:-translate-y-2 transition-transform duration-300">
              <Smartphone className="text-teal-500" size={40} />
              <div>
                <h4 className="text-2xl font-bold text-slate-900 dark:text-white mb-1">Learn Anywhere</h4>
                <p className="text-slate-400 dark:text-slate-500 text-base font-medium">Courses and resources on any device.</p>
              </div>
            </div>

            {/* BiT Verified — full width with animated bar */}
            <div className="col-span-2 bg-slate-50 dark:bg-slate-900/60 border border-slate-100 dark:border-slate-800 rounded-3xl p-10 hover:border-teal-200 dark:hover:border-teal-700 transition-all duration-300">
              <div className="flex items-center justify-between mb-5">
                <div>
                  <h4 className="text-xl font-bold text-slate-900 dark:text-white mb-1">BiT Department Endorsed</h4>
                  <p className="text-slate-500 dark:text-slate-400 text-sm font-medium">
                    Roadmaps and courses are created and verified by the BiT department and experienced teachers.
                  </p>
                </div>
                <div className="w-16 h-16 shrink-0 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-full flex items-center justify-center text-careermap-teal dark:text-teal-400 font-black text-lg shadow-sm ml-4">
                  100%
                </div>
              </div>
              {/* Animated progress bar */}
              <div className="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                <div
                  className={`h-full bg-careermap-teal rounded-full ${visible ? 'animate-progress-fill' : 'w-0'}`}
                />
              </div>
              <p className="text-xs text-slate-400 dark:text-slate-500 font-semibold uppercase tracking-widest mt-2">
                Curriculum coverage
              </p>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
};

export default ProblemSolution;
