
import React, { useState } from 'react';
import { 
  Send, Loader2, Share2, Target, 
  Rocket, Search, ArrowLeft, GitFork, 
  Layers, BookOpen, Clock, Youtube, FileText, Globe,
  CheckCircle2, AlertCircle, ArrowRight, Activity, ChevronDown, ChevronUp, Star, Atom, Trash2, Calendar
} from 'lucide-react';
import { generateRoadmap } from '../../services/geminiService';
import { createCourseFromRoadmap } from '../../services/courseService';
import { saveRoadmap, getUserRoadmaps, SavedRoadmap, deleteRoadmap } from '../../services/roadmapService';
import { DetailedRoadmap, RoadmapPhase, RoadmapTopic, Course } from '../../types';
import CourseView from './CourseView';

interface RoadmapGeneratorProps {
  onCourseCreated?: (course: Course) => void;
  userId?: string;
  initialQuery?: string;
  onBackToCurated?: () => void;
}

const RoadmapGenerator: React.FC<RoadmapGeneratorProps> = ({ onCourseCreated, userId = 'mock-user-id', initialQuery, onBackToCurated }) => {
  const [input, setInput] = useState(initialQuery || '');
  const [loading, setLoading] = useState(false);
  const [courseLoading, setCourseLoading] = useState(false);
  const [result, setResult] = useState<DetailedRoadmap | null>(null);
  const [generatedCourse, setGeneratedCourse] = useState<Course | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [viewMode, setViewMode] = useState<'input' | 'roadmap' | 'course'>('input');
  const [history, setHistory] = useState<SavedRoadmap[]>([]);
  const hasAutoGenerated = React.useRef(false);

  React.useEffect(() => {
    getUserRoadmaps(userId).then(setHistory);
  }, [userId]);

  React.useEffect(() => {
    if (initialQuery && !result && !loading && !hasAutoGenerated.current) {
        hasAutoGenerated.current = true;
        setInput(initialQuery);
        triggerGeneration(initialQuery);
    }
  }, [initialQuery]);
  
  const triggerGeneration = async (query: string) => {
    if (!query.trim()) return;
    setLoading(true);
    setError(null);
    try {
      const roadmap = await generateRoadmap(query);
      if (roadmap) {
        setResult(roadmap);
        setGeneratedCourse(null);
        
        saveRoadmap(roadmap, userId).then(saved => {
           if (saved) setHistory(prev => [saved, ...prev]);
        });
        
        setViewMode('roadmap');
      } else {
        setError("Failed to generate roadmap. Please try a different query.");
      }
    } catch (err) {
      setError("AI Service unavailable. Check console for API Key status.");
    } finally {
      setLoading(false);
    }
  };
  
  const handleGenerate = () => triggerGeneration(input);


  const handleDelete = async (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    try {
       await deleteRoadmap(id);
       setHistory(prev => prev.filter(h => h.id !== id));
    } catch (err) {
       console.error("Failed to delete", err);
    }
  };

  const handleCreateCourse = async () => {
    if (!result) return;
    setCourseLoading(true);
    setError(null);
    try {
       const course = await createCourseFromRoadmap(result.role, userId);
       if (course) {
         setGeneratedCourse(course);
         setViewMode('course');
         if (onCourseCreated) onCourseCreated(course);
       }
    } catch (e: any) {
       console.error(e);
       setError(e?.message || "Failed to create course. Please try again.");
    } finally {
       setCourseLoading(false);
    }
  };

  const [expandedTopic, setExpandedTopic] = useState<string | null>(null);

  const toggleTopic = (id: string) => {
    setExpandedTopic(expandedTopic === id ? null : id);
  };

  const getResourceIcon = (type: string) => {
    switch(type) {
      case 'video': return <Youtube size={16} className="text-red-500" />;
      case 'course': return <BookOpen size={16} className="text-indigo-500" />;
      case 'documentation': return <FileText size={16} className="text-slate-500" />;
      default: return <Globe size={16} className="text-emerald-500" />;
    }
  };

  const RoadmapView = ({ roadmap }: { roadmap: DetailedRoadmap }) => (
    <div className="animate-reveal max-w-7xl mx-auto space-y-12 pb-24">
      {/* Dynamic Header */}
      <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-8">
        <div className="space-y-1">
          <button onClick={() => setViewMode('input')} className="group flex items-center gap-3 text-slate-400 hover:text-secondary transition-colors font-bold text-xs uppercase tracking-widest mb-2">
            <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" /> Back to Generator
          </button>
          <h1 className="text-4xl md:text-5xl font-display font-bold text-primary dark:text-white tracking-tighter">
            Protocol: <span className="text-secondary">{roadmap.role}</span>
          </h1>
          <p className="text-sm font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">
            AI Architected Path • Verified for Industry Standards
          </p>
        </div>
        <div className="flex gap-4">
           <button className="glass dark:bg-slate-900/50 px-6 py-4 rounded-2xl border border-slate-100 dark:border-slate-800 flex items-center gap-3 hover:bg-white transition-all text-xs font-black uppercase tracking-widest text-slate-600">
             <Share2 size={16} /> Share
           </button>
           <button 
             onClick={handleCreateCourse}
             disabled={courseLoading}
             className="bg-secondary text-white px-8 py-4 rounded-2xl font-black uppercase tracking-widest text-[10px] shadow-xl hover:scale-105 active:scale-95 transition-all flex items-center gap-2 disabled:opacity-75 disabled:cursor-wait"
           >
             {courseLoading ? <Loader2 className="animate-spin" size={16} /> : <BookOpen size={16} />}
             Create Full Course
           </button>
        </div>
      </header>

      {/* Stats Grid */}
      <div className="grid md:grid-cols-12 gap-6">
        {/* Main Info Card */}
        <div className="md:col-span-8 bg-gradient-to-br from-indigo-900 to-slate-900 rounded-[3rem] p-10 md:p-14 text-white relative overflow-hidden shadow-2xl shadow-indigo-900/20">
          <div className="absolute top-0 right-0 p-10 opacity-10 pointer-events-none">
             <Target size={300} strokeWidth={0.5} />
          </div>
          <div className="relative z-10 flex flex-col h-full justify-between gap-8">
             <div>
                <div className="inline-flex items-center gap-2 bg-white/10 border border-white/20 px-4 py-1.5 rounded-full text-[10px] font-black uppercase tracking-widest mb-6 backdrop-blur-md">
                   Core Architecture
                </div>
                <h2 className="text-3xl md:text-4xl font-display font-bold mb-4 tracking-tight leading-tight">{roadmap.title}</h2>
                <p className="text-white/70 text-lg font-medium leading-relaxed max-w-2xl">{roadmap.description}</p>
             </div>
             
             <div className="flex flex-wrap gap-4">
                <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-4 flex items-center gap-3 pr-8">
                   <div className="p-2 bg-white/10 rounded-lg text-white"><Clock size={20} /></div>
                   <div>
                      <p className="text-[9px] font-black uppercase tracking-widest text-white/50">Est. Time</p>
                      <p className="text-lg font-bold">~6 Months</p>
                   </div>
                </div>
                <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-4 flex items-center gap-3 pr-8">
                   <div className="p-2 bg-white/10 rounded-lg text-white"><Layers size={20} /></div>
                   <div>
                      <p className="text-[9px] font-black uppercase tracking-widest text-white/50">Modules</p>
                      <p className="text-lg font-bold">{roadmap.phases.length} Phases</p>
                   </div>
                </div>
             </div>
          </div>
        </div>

        {/* Progress Card */}
        <div className="md:col-span-4 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-[3rem] p-10 flex flex-col items-center justify-center text-center shadow-sm">
           <div className="w-20 h-20 bg-emerald-50 text-emerald-500 rounded-full flex items-center justify-center mb-6">
              <Activity size={32} />
           </div>
           <p className="text-[10px] font-black text-slate-400 uppercase tracking-[0.3em] mb-2">Completion</p>
           <h3 className="text-4xl font-display font-bold text-primary dark:text-white">0%</h3>
           <p className="mt-4 text-sm font-medium text-slate-500">Start your journey today.</p>
        </div>
      </div>

      {/* Timeline Layout */}
      <div className="relative pt-10">
         <div className="absolute left-[29px] md:left-1/2 top-0 bottom-0 w-px bg-slate-200 dark:bg-slate-800 md:-ml-0.5"></div>

         <div className="space-y-16">
            {roadmap.phases.map((phase, idx) => (
              <div key={idx} className={`relative flex flex-col md:flex-row gap-8 items-start ${idx % 2 === 0 ? 'md:flex-row-reverse' : ''}`}>
                 
                 {/* Center Node */}
                 <div className="absolute left-[13px] md:left-1/2 top-8 w-8 h-8 bg-white dark:bg-slate-900 border-4 border-indigo-500 rounded-full z-10 md:-ml-4 shadow-lg shadow-indigo-500/30 flex items-center justify-center">
                    <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full"></div>
                 </div>

                 {/* Card */}
                 <div className="ml-16 md:ml-0 w-full md:w-[calc(50%-40px)] group perspective">
                    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 transition-all duration-500 hover:shadow-2xl hover:shadow-indigo-500/10 hover:border-indigo-500/30">
                       <div className="flex justify-between items-start mb-6">
                          <span className="bg-indigo-50 dark:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 px-3 py-1.5 rounded-xl text-[10px] font-black uppercase tracking-widest">{phase.duration}</span>
                          <span className="text-2xl font-display font-bold text-slate-200 dark:text-slate-800">0{idx + 1}</span>
                       </div>
                       
                       <h3 className="text-2xl font-display font-bold text-slate-800 dark:text-slate-100 mb-3">{phase.title}</h3>
                       <p className="text-slate-500 dark:text-slate-400 font-medium leading-relaxed mb-8">{phase.description}</p>
                       
                       {/* Topics Dropdowns */}
                       <div className="space-y-3">
                          {phase.topics?.map((topic, topicIdx) => {
                             const topicId = `${idx}-${topicIdx}`;
                             const isExpanded = expandedTopic === topicId;
                             
                             return (
                                <div key={topicIdx} className="border border-slate-100 dark:border-slate-800 rounded-2xl overflow-hidden bg-slate-50/50 dark:bg-slate-950/30">
                                   <button 
                                     onClick={() => toggleTopic(topicId)}
                                     className="w-full flex items-center justify-between p-4 hover:bg-slate-100 dark:hover:bg-slate-900 transition-colors"
                                   >
                                      <div className="flex items-center gap-3">
                                         <div className={`p-1.5 rounded-lg ${isExpanded ? 'bg-indigo-500 text-white' : 'bg-slate-200 text-slate-500'}`}>
                                            <Atom size={16} />
                                         </div>
                                         <span className="font-bold text-sm text-slate-700 dark:text-slate-200">{topic.title}</span>
                                      </div>
                                      {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                                   </button>
                                   
                                   {isExpanded && (
                                      <div className="p-4 pt-0 border-t border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 animate-in slide-in-from-top-2 duration-200">
                                         <div className="mb-4">
                                            <p className="text-[10px] uppercase font-black text-slate-400 tracking-wider mb-2 mt-4">Key Concepts</p>
                                            <div className="flex flex-wrap gap-2">
                                               {topic.concepts.map((concept, i) => (
                                                  <span key={i} className="text-xs font-medium bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 px-2 py-1 rounded-md border border-slate-200 dark:border-slate-700">
                                                     {concept}
                                                  </span>
                                               ))}
                                            </div>
                                         </div>

                                         <div className="space-y-2">
                                            <p className="text-[10px] uppercase font-black text-slate-400 tracking-wider mb-2">Recommended Resources</p>
                                            {topic.resources.map((res, i) => (
                                               <a key={i} href={res.url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-3 p-2 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-800 group/link transition-colors">
                                                  {getResourceIcon(res.type)}
                                                  <span className="text-xs font-bold text-slate-600 dark:text-slate-300 flex-1 truncate">{res.title}</span>
                                                  <ArrowRight size={12} className="opacity-0 group-hover/link:opacity-100 -translate-x-2 group-hover/link:translate-x-0 transition-all text-indigo-500" />
                                               </a>
                                            ))}
                                         </div>
                                      </div>
                                   )}
                                </div>
                             );
                          })}
                       </div>
                    </div>
                 </div>

                 {/* Spacer */}
                 <div className="hidden md:block md:w-[calc(50%-40px)]"></div>
              </div>
            ))}
         </div>
      </div>
    </div>
  );

  return (
    <div className="animate-reveal min-h-screen">
      {viewMode === 'input' ? (
        <div className="flex flex-col items-center justify-center py-20 px-4 max-w-4xl mx-auto text-center">
           {onBackToCurated && (
             <button
               onClick={onBackToCurated}
               className="self-start mb-8 flex items-center gap-2 text-slate-600 hover:text-secondary transition-colors font-semibold"
             >
               <ArrowLeft size={20} />
               <span>Back to Curated Roadmaps</span>
             </button>
           )}
           <div className="w-24 h-24 bg-gradient-to-tr from-slate-800 to-slate-900 rounded-[2rem] flex items-center justify-center text-white mb-10 shadow-2xl shadow-slate-900/10 ring-8 ring-slate-100 dark:ring-slate-800">
              <Rocket size={40} />
           </div>
           <h1 className="text-5xl md:text-7xl font-display font-bold text-slate-900 dark:text-white mb-8 tracking-tighter">
             Master <span className="text-secondary">Anything.</span>
           </h1>
           <p className="text-xl text-slate-500 dark:text-slate-400 mb-12 max-w-2xl font-medium leading-relaxed">
             From coding to cooking, startups to science. Our AI architect constructs a professional learning protocol for any goal.
           </p>
           
           <div className="w-full max-w-2xl relative group z-20">
              <div className="absolute -inset-1 bg-slate-200 dark:bg-slate-800 rounded-[2rem] blur opacity-25 group-hover:opacity-50 transition duration-1000"></div>
              <div className="relative flex items-center bg-white dark:bg-slate-900 rounded-[2rem] shadow-2xl p-2 border border-slate-100 dark:border-slate-800">
                 <Search className="ml-6 text-slate-400" size={24} />
                 <input 
                   type="text" 
                   value={input}
                   onChange={(e) => setInput(e.target.value)}
                   onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                   placeholder="e.g. Digital Marketing, Quantum Physics, French Cuisine..."
                   className="w-full bg-transparent border-none text-xl font-bold text-slate-800 dark:text-white placeholder:text-slate-300 focus:ring-0 px-6 py-5"
                 />
                 <button 
                  onClick={handleGenerate}
                  disabled={loading || !input.trim()}
                  className="bg-slate-900 text-white p-5 rounded-[1.5rem] hover:scale-105 active:scale-95 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-lg shadow-slate-900/20 aspect-square flex items-center justify-center"
                 >
                   {loading ? <Loader2 className="animate-spin" size={24} /> : <ArrowRight size={24} />}
                 </button>
              </div>
           </div>

           {error && (
             <div className="mt-8 flex items-center gap-3 text-red-600 bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-900/50 px-6 py-4 rounded-2xl text-sm font-bold animate-pulse">
               <AlertCircle size={20} />
               {error}
             </div>
           )}

           <div className="flex gap-3 mt-12 flex-wrap justify-center">
              {['Launch a Startup', 'Learn Piano', 'Data Science', 'Speak Japanese'].map(tag => (
                <button 
                  key={tag}
                  onClick={() => { setInput(tag); }}
                  className="px-6 py-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl text-xs font-bold text-slate-500 uppercase tracking-widest hover:border-slate-400 hover:text-slate-800 hover:shadow-lg hover:-translate-y-1 transition-all"
                >
                  {tag}
                </button>
              ))}
           </div>

           {history.length > 0 && (
             <div className="mt-24 w-full text-left animate-in slide-in-from-bottom-5 duration-500">
                <div className="flex items-center gap-4 mb-8">
                   <h3 className="text-xs font-black text-slate-400 uppercase tracking-[0.2em]">Previous Protocols</h3>
                   <div className="h-px flex-1 bg-slate-200 dark:bg-slate-800"></div>
                </div>
                
                <div className="grid md:grid-cols-2 gap-4">
                  {history.map(item => (
                    <div 
                      key={item.id} 
                      onClick={() => { setResult(item.road_data); setViewMode('roadmap'); }}
                      className="group bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 rounded-3xl cursor-pointer hover:border-indigo-500 dark:hover:border-indigo-500 hover:shadow-xl hover:shadow-indigo-500/10 transition-all flex justify-between items-start"
                    >
                       <div>
                          <div className="flex items-center gap-2 mb-2">
                             <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                             <span className="text-[10px] uppercase font-bold text-slate-400">{new Date(item.created_at).toLocaleDateString()}</span>
                          </div>
                          <h4 className="font-bold text-slate-800 dark:text-slate-200 text-lg group-hover:text-indigo-600 dark:group-hover:text-indigo-400 transition-colors">{item.role}</h4>
                          <p className="text-sm text-slate-500 mt-1 line-clamp-1">{item.title}</p>
                       </div>
                       <button 
                         onClick={(e) => handleDelete(e, item.id)}
                         className="p-2 text-slate-300 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-xl transition-colors opacity-0 group-hover:opacity-100"
                       >
                          <Trash2 size={16} />
                       </button>
                    </div>
                  ))}
                </div>
             </div>
           )}
        </div>
      ) : viewMode === 'course' && generatedCourse ? (
        <CourseView initialCourseData={generatedCourse} onBack={() => { setResult(null); setViewMode('input'); }} />
      ) : (
        result && <RoadmapView roadmap={result} />
      )}
    </div>
  );
};


export default RoadmapGenerator;
