<?php
require_once __DIR__ . '/../Models/CuratedRoadmap.php';
require_once __DIR__ . '/../Models/EducationalResource.php';
require_once __DIR__ . '/../Models/User.php';
require_once __DIR__ . '/../Helpers/JWTHelper.php';

class AdminController {
    private $roadmapModel, $resourceModel, $userModel, $jwtHelper;
    public function __construct() {
        $this->roadmapModel = new CuratedRoadmap();
        $this->resourceModel = new EducationalResource();
        $this->userModel = new User();
        $this->jwtHelper = new JWTHelper();
    }
    private function checkPermission($role = 'teacher') {
        $headers = \getallheaders();
        $token = str_replace('Bearer ', '', $headers['Authorization'] ?? '');
        $decoded = $this->jwtHelper->validateToken($token);
        if (!$decoded) { http_response_code(401); echo json_encode(['error'=>'Unauthorized']); exit(); }
        $user = $this->userModel->findById($decoded->user_id);
        if (!$user) { http_response_code(401); echo json_encode(['error'=>'User not found']); exit(); }
        if ($role === 'admin' && $user['role'] !== 'admin') { http_response_code(403); echo json_encode(['error'=>'Admin access required']); exit(); }
        if ($role === 'teacher' && !in_array($user['role'], ['teacher','admin'])) { http_response_code(403); echo json_encode(['error'=>'Teacher or Admin access required']); exit(); }
        if ($user['role'] === 'teacher' && ($user['account_status'] ?? 'active') === 'pending') { http_response_code(403); echo json_encode(['error'=>'Account pending approval']); exit(); }
        return $user;
    }
    private function db() { $d = new Database(); return $d->getConnection(); }
    private function safeCount($conn, $sql) { try { return (int)$conn->query($sql)->fetchColumn(); } catch (\Exception $e) { return 0; } }
    private function ensureUserColumns($conn) {
        $cols = ["ALTER TABLE users ADD COLUMN IF NOT EXISTS role_request ENUM('student','teacher','admin','bit') DEFAULT 'student'","ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status ENUM('pending','active','rejected') DEFAULT 'active'","ALTER TABLE users ADD COLUMN IF NOT EXISTS approval_notes TEXT NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS requested_at TIMESTAMP NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by INT NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS institution VARCHAR(255) NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS years_experience INT NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS expertise_areas JSON NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS qualifications JSON NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS student_id VARCHAR(100) NULL","ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(100) NULL"];
        foreach ($cols as $sql) { try { $conn->exec($sql); } catch (\Exception $e) {} }
        try { $conn->exec("UPDATE users SET account_status='active' WHERE account_status IS NULL OR account_status=''"); } catch (\Exception $e) {}
    }
    public function getAnalytics() {
        $this->checkPermission('admin'); $conn = $this->db();
        echo json_encode(['total_users'=>$this->safeCount($conn,"SELECT COUNT(*) FROM users"),'total_students'=>$this->safeCount($conn,"SELECT COUNT(*) FROM users WHERE role='student'"),'total_teachers'=>$this->safeCount($conn,"SELECT COUNT(*) FROM users WHERE role='teacher'"),'total_admins'=>$this->safeCount($conn,"SELECT COUNT(*) FROM users WHERE role='admin'"),'total_roadmaps'=>$this->safeCount($conn,"SELECT COUNT(*) FROM curated_roadmaps WHERE status='published'"),'total_resources'=>$this->safeCount($conn,"SELECT COUNT(*) FROM educational_resources"),'pending_resources'=>$this->safeCount($conn,"SELECT COUNT(*) FROM educational_resources WHERE status='pending'"),'approved_resources'=>$this->safeCount($conn,"SELECT COUNT(*) FROM educational_resources WHERE status='approved'"),'rejected_resources'=>$this->safeCount($conn,"SELECT COUNT(*) FROM educational_resources WHERE status='rejected'"),'pending_approvals'=>$this->safeCount($conn,"SELECT COUNT(*) FROM users WHERE account_status='pending'"),'popular_roadmaps'=>$this->roadmapModel->getPopular(5),'recent_activity'=>[]]);
    }
    public function getPendingApprovals() {
        $this->checkPermission('admin'); $conn = $this->db(); $this->ensureUserColumns($conn);
        try { $stmt = $conn->query("SELECT id,name,email,role,COALESCE(role_request,role) as role_request,COALESCE(account_status,'active') as account_status,institution,years_experience,expertise_areas,qualifications,bio,requested_at,created_at FROM users WHERE account_status='pending' ORDER BY requested_at DESC"); $rows = $stmt->fetchAll(PDO::FETCH_ASSOC); foreach ($rows as &$u) { if (!empty($u['expertise_areas'])) $u['expertise_areas']=json_decode($u['expertise_areas'],true); if (!empty($u['qualifications'])) $u['qualifications']=json_decode($u['qualifications'],true); } echo json_encode($rows); } catch (\Exception $e) { echo json_encode([]); }
    }
    public function approveRoleRequest($userId) {
        $admin = $this->checkPermission('admin'); $data = json_decode(file_get_contents("php://input"),true); $notes = $data['notes']??''; $conn = $this->db(); $this->ensureUserColumns($conn);
        $stmt = $conn->prepare("SELECT COALESCE(role_request,'teacher') as role_request FROM users WHERE id=?"); $stmt->execute([$userId]); $row = $stmt->fetch(PDO::FETCH_ASSOC);
        if (!$row) { http_response_code(404); echo json_encode(['error'=>'User not found']); return; }
        $stmt = $conn->prepare("UPDATE users SET role=?,account_status='active',approval_notes=?,approved_at=NOW(),approved_by=? WHERE id=?");
        if ($stmt->execute([$row['role_request'],$notes,$admin['id'],$userId])) echo json_encode(['success'=>true,'message'=>'Approved']); else { http_response_code(500); echo json_encode(['error'=>'Failed']); }
    }
    public function rejectRoleRequest($userId) {
        $admin = $this->checkPermission('admin'); $data = json_decode(file_get_contents("php://input"),true); $notes = $data['notes']??''; $conn = $this->db(); $this->ensureUserColumns($conn);
        $stmt = $conn->prepare("UPDATE users SET account_status='rejected',approval_notes=?,approved_at=NOW(),approved_by=? WHERE id=?");
        if ($stmt->execute([$notes,$admin['id'],$userId])) echo json_encode(['success'=>true,'message'=>'Rejected']); else { http_response_code(500); echo json_encode(['error'=>'Failed']); }
    }
    public function getAllUsers() { $this->checkPermission('admin'); $conn=$this->db(); echo json_encode($conn->query("SELECT id,name,email,role,academic_year,xp,streak,created_at FROM users ORDER BY created_at DESC")->fetchAll()); }
    public function updateUserRole($id) { $this->checkPermission('admin'); $data=json_decode(file_get_contents("php://input"),true); if(!isset($data['role'])||!in_array($data['role'],['student','teacher','admin','bit'])){http_response_code(400);echo json_encode(['error'=>'Valid role required']);return;} if($this->userModel->update($id,['role'=>$data['role']])) echo json_encode(['message'=>'Updated']); else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function createRoadmap() { $user=$this->checkPermission('teacher'); $data=json_decode(file_get_contents("php://input"),true); if(!isset($data['title'])||!isset($data['phases'])){http_response_code(400);echo json_encode(['error'=>'Title and phases required']);return;} $id=$this->roadmapModel->create(['title'=>$data['title'],'description'=>$data['description']??'','category'=>$data['category']??'General','difficulty_level'=>$data['difficulty_level']??'beginner','estimated_duration'=>$data['estimated_duration']??'','created_by'=>$user['id'],'status'=>$data['status']??'published','tags'=>json_encode($data['tags']??[]),'phases'=>json_encode($data['phases']),'thumbnail_url'=>$data['thumbnail_url']??null]); if($id){if(($data['status']??'published')==='published')$this->enrollAllStudents($id,$data['title']);http_response_code(201);echo json_encode(['message'=>'Created','roadmap_id'=>$id]);}else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function getRoadmaps() { $this->checkPermission('teacher'); $f=array_filter(['status'=>$_GET['status']??null,'category'=>$_GET['category']??null,'difficulty_level'=>$_GET['difficulty_level']??null,'search'=>$_GET['search']??null,'limit'=>isset($_GET['limit'])?(int)$_GET['limit']:50,'offset'=>isset($_GET['offset'])?(int)$_GET['offset']:0],function($v){return $v!==null;}); $rs=$this->roadmapModel->getAll($f); foreach($rs as &$r){$r['tags']=json_decode($r['tags']??'[]',true);$r['phases']=json_decode($r['phases']??'[]',true);} echo json_encode($rs); }
    public function getRoadmap($id) { $this->checkPermission('teacher'); $r=$this->roadmapModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} $r['tags']=json_decode($r['tags']??'[]',true);$r['phases']=json_decode($r['phases']??'[]',true); echo json_encode($r); }
    public function updateRoadmap($id) { $user=$this->checkPermission('teacher'); $data=json_decode(file_get_contents("php://input"),true); $r=$this->roadmapModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($user['role']!=='admin'&&$r['created_by']!=$user['id']){http_response_code(403);echo json_encode(['error'=>'Forbidden']);return;} $u=[];foreach(['title','description','category','difficulty_level','estimated_duration','status','thumbnail_url'] as $f)if(isset($data[$f]))$u[$f]=$data[$f];if(isset($data['tags']))$u['tags']=json_encode($data['tags']);if(isset($data['phases']))$u['phases']=json_encode($data['phases']); if($this->roadmapModel->update($id,$u))echo json_encode(['message'=>'Updated']);else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function deleteRoadmap($id) { $user=$this->checkPermission('teacher'); $r=$this->roadmapModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($user['role']!=='admin'&&$r['created_by']!=$user['id']){http_response_code(403);echo json_encode(['error'=>'Forbidden']);return;} if($this->roadmapModel->delete($id))echo json_encode(['message'=>'Deleted']);else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function publishRoadmap($id) { $user=$this->checkPermission('teacher'); $r=$this->roadmapModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($user['role']!=='admin'&&$r['created_by']!=$user['id']){http_response_code(403);echo json_encode(['error'=>'Forbidden']);return;} if($this->roadmapModel->update($id,['status'=>'published'])){$c=$this->enrollAllStudents($id,$r['title']);echo json_encode(['message'=>'Published','enrolled_count'=>$c]);}else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    private function enrollAllStudents($rid,$title) { $conn=$this->db(); $ss=$conn->query("SELECT id FROM users WHERE role='student' AND (account_status='active' OR account_status IS NULL)")->fetchAll(PDO::FETCH_ASSOC); foreach($ss as $s){$conn->prepare("INSERT IGNORE INTO roadmap_enrollments (user_id,roadmap_id,status) VALUES (?,?,'active')")->execute([$s['id'],$rid]);$conn->prepare("INSERT INTO notifications (user_id,type,title,message,link) VALUES (?,'new_roadmap',?,?,'/roadmaps')")->execute([$s['id'],'New Roadmap: '.$title,'Roadmap "'.$title.'" published.']);} try{$conn->prepare("UPDATE curated_roadmaps SET enrollments=(SELECT COUNT(*) FROM roadmap_enrollments WHERE roadmap_id=?) WHERE id=?")->execute([$rid,$rid]);}catch(\Exception $e){} return count($ss); }
    public function addCourseToRoadmap($rid) { $admin=$this->checkPermission('admin'); $data=json_decode(file_get_contents("php://input"),true); if(!isset($data['title'])||empty($data['modules'])){http_response_code(400);echo json_encode(['error'=>'Title and modules required']);return;} $r=$this->roadmapModel->getById($rid); if(!$r){http_response_code(404);echo json_encode(['error'=>'Roadmap not found']);return;} $conn=$this->db(); $stmt=$conn->prepare("INSERT INTO courses (title,description,category,level,modules,duration,author,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,NOW())"); $stmt->execute([$data['title'],$data['description']??'',$r['category']??'General',$data['level']??'Intermediate',json_encode($data['modules']),$data['duration']??'',$admin['name'],$admin['id']]); $cid=$conn->lastInsertId(); if(!$cid){http_response_code(500);echo json_encode(['error'=>'Failed']);return;} $conn->exec("CREATE TABLE IF NOT EXISTS roadmap_courses (id INT AUTO_INCREMENT PRIMARY KEY,roadmap_id INT NOT NULL,course_id INT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY ul(roadmap_id,course_id),FOREIGN KEY(roadmap_id) REFERENCES curated_roadmaps(id) ON DELETE CASCADE,FOREIGN KEY(course_id) REFERENCES courses(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"); $conn->prepare("INSERT IGNORE INTO roadmap_courses (roadmap_id,course_id) VALUES (?,?)")->execute([$rid,$cid]); $ss=$conn->query("SELECT id FROM users WHERE role='student' AND (account_status='active' OR account_status IS NULL)")->fetchAll(PDO::FETCH_ASSOC); foreach($ss as $s){if($r['status']==='published')$conn->prepare("INSERT IGNORE INTO roadmap_enrollments (user_id,roadmap_id,status) VALUES (?,?,'active')")->execute([$s['id'],$rid]);$conn->prepare("INSERT IGNORE INTO course_enrollments (user_id,course_id,enrolled_at) VALUES (?,?,NOW())")->execute([$s['id'],$cid]);$conn->prepare("INSERT INTO notifications (user_id,type,title,message,link) VALUES (?,'new_resource',?,?,'/courses')")->execute([$s['id'],'New Course: '.$data['title'],'Course "'.$data['title'].'" added.']);} http_response_code(201);echo json_encode(['message'=>'Course created','course_id'=>$cid,'enrolled_count'=>count($ss)]); }
    public function createResource() { $user=$this->checkPermission('teacher'); $data=json_decode(file_get_contents("php://input"),true); if(!isset($data['title'])||!isset($data['resource_type'])){http_response_code(400);echo json_encode(['error'=>'Title and resource_type required']);return;} $id=$this->resourceModel->create(['title'=>$data['title'],'description'=>$data['description']??'','resource_type'=>$data['resource_type'],'file_path'=>$data['file_path']??null,'external_url'=>$data['external_url']??null,'category'=>$data['category']??'General','tags'=>json_encode($data['tags']??[]),'uploaded_by'=>$user['id'],'file_size'=>$data['file_size']??0,'file_type'=>$data['file_type']??null,'status'=>$user['role']==='admin'?'approved':'pending']); if($id){http_response_code(201);echo json_encode(['message'=>'Resource created','resource_id'=>$id]);}else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function getResources() { $this->checkPermission('teacher'); $f=array_filter(['status'=>$_GET['status']??null,'resource_type'=>$_GET['resource_type']??null,'category'=>$_GET['category']??null,'search'=>$_GET['search']??null,'limit'=>isset($_GET['limit'])?(int)$_GET['limit']:50,'offset'=>isset($_GET['offset'])?(int)$_GET['offset']:0],function($v){return $v!==null;}); $rs=$this->resourceModel->getAll($f); foreach($rs as &$r){$r['tags']=json_decode($r['tags']??'[]',true);} echo json_encode($rs); }
    public function updateResource($id) { $user=$this->checkPermission('teacher'); $data=json_decode(file_get_contents("php://input"),true); $r=$this->resourceModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($user['role']!=='admin'&&$r['uploaded_by']!=$user['id']){http_response_code(403);echo json_encode(['error'=>'Forbidden']);return;} $u=[];foreach(['title','description','resource_type','external_url','category'] as $f)if(isset($data[$f]))$u[$f]=$data[$f];if(isset($data['tags']))$u['tags']=json_encode($data['tags']); if($this->resourceModel->update($id,$u))echo json_encode(['message'=>'Updated']);else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function deleteResource($id) { $user=$this->checkPermission('teacher'); $r=$this->resourceModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($user['role']!=='admin'&&$r['uploaded_by']!=$user['id']){http_response_code(403);echo json_encode(['error'=>'Forbidden']);return;} if($this->resourceModel->delete($id))echo json_encode(['message'=>'Deleted']);else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function approveResource($id) { $this->checkPermission('admin'); $r=$this->resourceModel->getById($id); if(!$r){http_response_code(404);echo json_encode(['error'=>'Not found']);return;} if($this->resourceModel->approve($id)){$conn=$this->db();$ss=$conn->query("SELECT id FROM users WHERE role='student' AND (account_status='active' OR account_status IS NULL)")->fetchAll(PDO::FETCH_ASSOC);foreach($ss as $s)$conn->prepare("INSERT INTO notifications (user_id,type,title,message,link) VALUES (?,'new_resource',?,?,'/library')")->execute([$s['id'],'New Material: '.$r['title'],'Material "'.$r['title'].'" added.']);echo json_encode(['message'=>'Approved','notified_count'=>count($ss)]);}else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function rejectResource($id) { $this->checkPermission('admin'); if($this->resourceModel->reject($id))echo json_encode(['message'=>'Rejected']);else{http_response_code(500);echo json_encode(['error'=>'Failed']);} }
    public function getPendingResources() { $this->checkPermission('admin'); $rs=$this->resourceModel->getPending(); foreach($rs as &$r){$r['tags']=json_decode($r['tags']??'[]',true);} echo json_encode($rs); }
}
