import React from 'react';
import { FileText, CheckCircle2, AlertTriangle, Scale, UserPlus, Zap } from 'lucide-react';

const TermsOfServicePage: React.FC = () => {
  const lastUpdated = "April 18, 2026";

  const terms = [
    {
      title: "1. Acceptance of Terms",
      icon: CheckCircle2,
      content: "By accessing and using CareerGuide, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. These terms apply to all students, teachers, and visitors."
    },
    {
      title: "2. Eligibility & Accounts",
      icon: UserPlus,
      content: "To use CareerGuide, you must be a current student or staff member of Bahir Dar University. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account."
    },
    {
      title: "3. AI Content Disclaimer",
      icon: Zap,
      content: "The career roadmaps and course recommendations are generated by Artificial Intelligence. While we strive for accuracy, CareerGuide does not guarantee that AI-generated content is 100% correct or reflects actual job market requirements at all times. Use them as guidance, not absolute authority."
    },
    {
      title: "4. Prohibited Conduct",
      icon: AlertTriangle,
      content: "Users may not: (a) Attempt to scrape AI-generated roadmaps for commercial use; (b) Upload malicious code to the library; (c) Use the platform to harass other BiT community members; (d) Reverse engineer the AI recommendation logic."
    },
    {
      title: "5. Intellectual Property",
      icon: Scale,
      content: "CareerGuide and its original content, features, and functionality are owned by the platform creators and are protected by international copyright and trademark laws. User-uploaded materials in the library remain the property of the original uploader."
    }
  ];

  return (
    <div className="pt-32 pb-20 bg-white dark:bg-slate-950 min-h-screen">
      <div className="max-w-[900px] mx-auto px-6">
        
        {/* Header */}
        <div className="mb-16 animate-fade-in-up text-center md:text-left">
          <div className="w-16 h-16 bg-slate-900 dark:bg-slate-800 text-teal-400 rounded-2xl flex items-center justify-center mb-6 shadow-xl mx-auto md:mx-0">
            <FileText size={32} />
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 dark:text-white mb-4 tracking-tight">
            Terms of Service
          </h1>
          <p className="text-slate-500 dark:text-slate-400 font-medium">
            Effective Date: {lastUpdated}
          </p>
        </div>

        {/* Introduction */}
        <div className="mb-20 p-10 bg-slate-50 dark:bg-slate-900 rounded-[2.5rem] border border-slate-100 dark:border-slate-800 animate-fade-in-up">
           <p className="text-xl text-slate-600 dark:text-slate-300 leading-relaxed font-medium m-0">
             "Welcome to CareerGuide. These terms govern your use of our AI-powered career platform. Our goal is to provide a safe, high-quality learning environment for the BiT community."
           </p>
        </div>

        {/* Terms List */}
        <div className="space-y-16 animate-fade-in-up" style={{ animationDelay: '0.2s' }}>
          {terms.map((term, i) => (
            <div key={i} className="relative pl-16 md:pl-24">
              {/* Number/Icon */}
              <div className="absolute left-0 top-0 w-12 h-12 md:w-16 md:h-16 rounded-2xl bg-white dark:bg-slate-900 border-2 border-slate-100 dark:border-slate-800 flex items-center justify-center text-careermap-teal shadow-sm">
                <term.icon size={24} className="md:size-[28px]" />
              </div>
              
              <h3 className="text-2xl font-bold text-slate-900 dark:text-white mb-4">
                {term.title}
              </h3>
              <p className="text-lg text-slate-500 dark:text-slate-400 leading-relaxed">
                {term.content}
              </p>
            </div>
          ))}
        </div>

        {/* Termination */}
        <div className="mt-32 p-12 rounded-[3rem] bg-careermap-navy text-white text-center animate-fade-in-up">
          <h2 className="text-3xl font-extrabold mb-6">Termination of Use</h2>
          <p className="text-teal-100/70 text-lg max-w-2xl mx-auto mb-8">
            We reserve the right to terminate or suspend your account and access to CareerGuide immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>
          <div className="h-px bg-white/10 w-24 mx-auto mb-8" />
          <p className="text-sm font-bold uppercase tracking-widest text-teal-400">
            End of Terms of Service
          </p>
        </div>

      </div>
    </div>
  );
};

export default TermsOfServicePage;
